model_name: DecisionTreeClassifier
artifact_path: basic_dt

tag_key: "model"
tag_value: "basic DT"

module_name: "sklearn.tree"
class_name: "DecisionTreeClassifier"

params:
  criterion: ["gini", "entropy", "log_loss"]
  max_depth: [2, 3, 5]
  min_samples_split: [2, 3, 4]