model_name: LogisticRegression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LogisticRegression"

params:
  solver: ["lbfgs", "liblinear", "saga"]
  tol: [0.1, 0.01, 0.001]
  max_iter: [50, 100, 200]