model_name: LogisticRegression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LogisticRegression"

params:
  critrerion: ["gini", "entropy", "log_loss"]
  max_depth: [None, 2, 5]
  min_samples_split: [2, 3, 4]