defaults:
  - _self_

folds: 3

evaluation_metric: "f1_weighted"
cv_evaluation_metric: "mean_test_f1"

pyfunc_predict_fn: "predict_proba"

metrics:
  # accuracy: "accuracy"
  f1: "f1_weighted"
  # recall: "recall_weighted"
  # precision: "precision_weighted"