defaults:
  - _self_
  - dt
  - mlp
  - lr

folds: 3

evaluation_metric: "f1"
cv_evaluation_metric: "mean_test_f1"

pyfunc_predict_fn: "predict_proba"

metrics:
  accuracy: "accuracy"
  f1: "f1"
  recall: "recall"
  precision: "precision"