channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.14.3
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - packaging==24.1
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.11.4
name: mlflow-env
