defaults:
  - _self_
  - data_version
  - model/model
  - experiment

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "lr, dt, mlp, transformer"

data:
  version: v1.0
  remote: localstore
  repo: "."
  path: data/raw/Test_Pandas.csv
  sample_size: 0.2
  random_state: 1
  target_col: category
  labels: 

paths:
  root_path: /home/datapaf/Desktop/mlops-final-project-iu-2024

datasets:
  target_col: "category"

reproducibility:
  seeds:
    - 42
    - 0
    - 1
    - 777
    - 7
    - 25