defaults:
  - _self_
  - data/sample
  - data_version
  - model/model
  - experiment

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: "dt, mlp, lr"

data:
  version: v1.0
  remote: localstore
  repo: "."
  path: data/raw/Test_Pandas.csv
  sample_size: 0.2
  random_state: 1